list=(5,8,1,7,3,9,4)
print("List of integers created:  ,"list)
list(2)=6
print("int added at position 2:  ,"list)
list.remove(9)
print(int 9 removed: ,"list)
list.append(11)
print("int 11 added at end :  ,"list)
list.sort()
print("list sorted:  ,"list)
list.pop()
print("last int removed:  ,"list)
list.reverse()
print("list reversed:  ,"list)
